# Generated by Django 6.0.2 on 2026-02-21 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_recipe_notes_recipestep'),
        ('ingredient_store', '0002_alter_onhandingredient_ingredient_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='onhandingredient',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='onhandingredient',
            name='ingredient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='on_hand', to='api.ingredient'),
        ),
    ]
