# Generated by Django 6.0.2 on 2026-02-20 21:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NutritionStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_unit', models.CharField(choices=[('kg', 'Kilogram'), ('L', 'Liter'), ('pc', 'Piece / Count')], default='kg', help_text='The base unit for the nutrition stats (e.g., per kg, per liter, etc.)', max_length=4)),
                ('kcal_per_unit', models.FloatField(blank=True, help_text='Calories (Kcal) per base unit', null=True)),
                ('fat_saturated_grams_per_unit', models.FloatField(blank=True, help_text='Saturated fat (g) per base unit', null=True)),
                ('fat_trans_grams_per_unit', models.FloatField(blank=True, help_text='Trans fat (g) per base unit', null=True)),
                ('carbohydrate_fiber_grams_per_unit', models.FloatField(blank=True, help_text='Fiber (g) per base unit', null=True)),
                ('carbohydrate_sugar_grams_per_unit', models.FloatField(blank=True, help_text='Sugars (g) per base unit', null=True)),
                ('protein_grams_per_unit', models.FloatField(blank=True, help_text='Protein (g) per base unit', null=True)),
                ('cholesterol_milligrams_per_unit', models.FloatField(blank=True, help_text='Cholesterol (mg) per base unit', null=True)),
                ('sodium_milligrams_per_unit', models.FloatField(blank=True, help_text='Sodium (mg) per base unit', null=True)),
                ('potassium_milligrams_per_unit', models.FloatField(blank=True, help_text='Potassium (mg) per base unit', null=True)),
                ('calcium_milligrams_per_unit', models.FloatField(blank=True, help_text='Calcium (mg) per base unit', null=True)),
                ('iron_milligrams_per_unit', models.FloatField(blank=True, help_text='Iron (mg) per base unit', null=True)),
                ('vitamin_a_milligrams_per_unit', models.FloatField(blank=True, help_text='Vitamin A (mg) per base unit', null=True)),
                ('vitamin_c_milligrams_per_unit', models.FloatField(blank=True, help_text='Vitamin C (mg) per base unit', null=True)),
                ('vitamin_d_milligrams_per_unit', models.FloatField(blank=True, help_text='Vitamin D (mg) per base unit', null=True)),
                ('ingredient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nutrition_stats', to='api.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField()),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('L', 'Liter'), ('pc', 'Piece / Count')], default='kg', help_text='The unit multiplier for the ingredient quantity (e.g., kg, liter, piece, etc.)', max_length=4)),
                ('notes', models.TextField(blank=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ingredient')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_list', to='api.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='api.RecipeIngredient', to='api.ingredient'),
        ),
    ]
