# Generated by Django 6.0.2 on 2026-02-22 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20260222_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=256)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='api.ingredient')),
            ],
            options={
                'indexes': [models.Index(fields=['alias'], name='api_ingredi_alias_24dd7d_idx')],
                'unique_together': {('ingredient', 'alias')},
            },
        ),
    ]
