# Generated by Django 6.0.2 on 2026-02-22 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_ingredientalias'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ingredientalias',
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name='ingredientalias',
            name='api_ingredi_alias_24dd7d_idx',
        ),
        migrations.DeleteModel(
            name='IngredientAlias',
        ),
    ]
