# Generated by Django 6.0.2 on 2026-02-22 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0007_source_quantity_source_quantity_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scraper',
            old_name='cached_url',
            new_name='cached_source',
        ),
    ]
