# Generated by Django 6.0.2 on 2026-02-22 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20260222_0016'),
        ('scraper', '0011_source_cached_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfirmableRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source_url', models.CharField(blank=True, max_length=200)),
                ('cook_time_minutes', models.IntegerField(blank=True, null=True)),
                ('prep_time_minutes', models.IntegerField(blank=True, null=True)),
                ('servings', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmableRecipeIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.CharField(max_length=200)),
                ('confidence', models.FloatField()),
                ('quantity', models.FloatField(help_text="Quantity in base units (e.g., grams, liters, pieces), defined by the ingredient's nutrition stats)")),
                ('best_guess_ingredient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.ingredient')),
                ('confirmable_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_list', to='scraper.confirmablerecipe')),
            ],
        ),
        migrations.AddField(
            model_name='confirmablerecipe',
            name='ingredients',
            field=models.ManyToManyField(blank=True, to='scraper.confirmablerecipeingredient'),
        ),
        migrations.CreateModel(
            name='ConfirmableRecipeStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField()),
                ('description', models.TextField()),
                ('confirmable_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps_list', to='scraper.confirmablerecipe')),
            ],
        ),
        migrations.AddField(
            model_name='confirmablerecipe',
            name='steps',
            field=models.ManyToManyField(blank=True, to='scraper.confirmablerecipestep'),
        ),
    ]
